### ISSUE TITLE
You can no longer create legacy tokens. How do you get a token now?

### ISSUE THREAD

**Issue by AndrewSav** [zach-snell/slack-export#33]
Slack disabled creation of legacy tokens. What is the new method of making this tool work?

**Comment by gonzalognzl** [comment]
You should create a Slack app and install it on your workspace. You will generate a bot token (`xoxb-`)

To get private channels history, you should:

1. update code with pull request #32 
2. add the bot/app to each private channel you want to export

I've just done this and it's working fine.

**Comment by josephj** [comment]
Hey @gonzalognzl 

Thanks for creating that PR. However, I got the following error. 

```
Traceback (most recent call last):
  File "slack_export.py", line 396, in <module>
    bootstrapKeyValues()
  File "slack_export.py", line 269, in bootstrapKeyValues
    channels = list(filter(lambda y:  y.get('is_channel',False) and y['name'] not in excluded, conversations))
  File "slack_export.py", line 269, in <lambda>
    channels = list(filter(lambda y:  y.get('is_channel',False) and y['name'] not in excluded, conversations))
TypeError: argument of type 'NoneType' is not iterable
```

Any ideas?

**Comment by gonzalognzl** [comment]
@josephj I'm running [this one](https://github.com/gonzalognzl/slack-export/blob/master/slack_export.py) whit none errors. 
python 3 support only

**Comment by AndrewSav** [comment]
> add the bot/app to each private channel you want to export

I'm sure there is any easier way. what if I have 100+ channels? What if I don't what to bother people with bots popping in an out?

**Comment by lumbric** [comment]
The new API system introduces more fine grained control over permissions of your apps. That's a plus for 3rd party apps, but a bit of a downside for this simple script (it's probably easier to read the script and verify that it won't do any harm than setting the permissions).

Got to https://api.slack.com/apps and _Create New App_. Then click on your app (also [here](https://api.slack.com/apps)) and go to _Add features and functionality -> Permissions -> Scopes_ and add the following scopes User Token Scopes:

- channels:history
- channels:read
- groups:history
- groups:read
- im:history
- im:read
- mpim:history
- mpim:read
- users:read

Then install the app in your workspace, accept the permissions and copy the token. It says _OAuth Access Token_, tbh I'm not really sure, but I think this should be the user token then.

Using [a slightly modified verison](https://github.com/lumbric/slack-export/tree/working-draft) of the fork by @gonzalognzl, I was then successful to run the export:

`python  slack_export.py --token xoxp-TOKEN`

I'm not entirely sure if this is the right way to do it, but it seems to work for me (without adding any bots to channels or DMs).

(I'll probably continue playing around with this a bit and keep this issue updated if I have any news.)

**Comment by AndrewSav** [comment]
@lumbric yes, thank you, this worked for me as well.

**Comment by celmaun** [comment]
@lumbric Sadly apps created after June 10th, 2020 can no longer access those API methods :(

**Comment by AndrewSav** [comment]
@Salmatron double-check you did not get that wrong. I think you did.

**Comment by AndrewSav** [comment]
@Salmatron I just tried creating a new app and it worked as per steps described above.

**Comment by jonmchan** [comment]
DMs were failing on me with gonzalognzl's version and my brand new token generated today August 16, 2020. I would receive the slacker.Error: method_deprecated error. I switched to cekees' version and everything exported for me without issue:  https://github.com/zach-snell/slack-export/pull/38. He switched to slackclient instead of slacker - guess they are using non-deprecated calls? 🤷

**Comment by lumbric** [comment]
@jonmchan I've used [this version](https://github.com/lumbric/slack-export/commits/working-draft), which is @gonzalognzl's version with [one more fix](https://github.com/lumbric/slack-export/commit/553e8be3af08652da06e50f35f2bb930941ab271) of a depricated API call. slacker is fine, it just provides a generic interface to the calls - you have to decide on the client side which calls to use and how to avoid the deprecated ones. I haven't tried slackclient yet, I guess both works fine if used correctly.

**Comment by jonmchan** [comment]
@lumbric your version is better than cekees as it maintains compatibility with slack-export-viewer. No deprecated API call failure nor any issues loading it up in slack-export-viewer. Thanks for sharing!

**Comment by kingram6865** [comment]
I've come across this error retrieving Direct Messages:
```
Making channels file
Fetching 1:1 DMs with U01CHVB66KU (name unknown)
Traceback (most recent call last):
  File "slack_export.py", line 424, in <module>
    fetchDirectMessages(selectedDms)
  File "slack_export.py", line 226, in fetchDirectMessages
    messages = getHistory(slack.im, dm['id'])
  File "slack_export.py", line 40, in getHistory
    count     = pageSize
  File "/home/kingram/.local/lib/python2.7/site-packages/slacker/__init__.py", line 606, in history
    'unreads': int(unreads)
  File "/home/kingram/.local/lib/python2.7/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/home/kingram/.local/lib/python2.7/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: method_deprecated
```

**Comment by filipedematos** [comment]
Hi all! So i've come across this error:

Successfully authenticated for team ***** ***** and user *****
Found 13 Users
Traceback (most recent call last):
  File "slack_export.py", line 345, in <module>
    bootstrapKeyValues()
  File "slack_export.py", line 245, in bootstrapKeyValues
    channels = slack.channels.list().body['channels']
  File "/Users/syox/Library/Python/2.7/lib/python/site-packages/slacker/__init__.py", line 428, in list
    'exclude_members': exclude_members})
  File "/Users/syox/Library/Python/2.7/lib/python/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/Users/syox/Library/Python/2.7/lib/python/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: method_deprecated

Can anyone suggest a solution? Thank you

**Comment by ehoppmann** [comment]
Thanks to everyone in this channel for sharing their work in keeping this tool working. 

Today I wanted to export a public channel, I was able to do so by

1. fetching lumbric's branch https://github.com/lumbric/slack-export/tree/working-draft
2. editing `slack_export.py` in the above code to insert the line `slack.conversations.join(channel['id'])` at line 172, that is, in the function `fetchPublicChannels` add that line to the loop over channels right before getHistory is called:
```
diff --git a/slack_export.py b/slack_export.py
index 8757eac..d173e12 100644
--- a/slack_export.py
+++ b/slack_export.py
@@ -169,6 +169,7 @@ def fetchPublicChannels(channels):
         print("Fetching history for Public Channel: {0}".format(channelDir))
         channelDir = channel['name'].encode('utf-8')
         mkdir( channelDir )
+        slack.conversations.join(channel['id'])
         messages = getHistory(slack.conversations, channel['id'])
         parseMessages( channelDir, messages, 'channel')

```
3. editing `__init__.py` in the slacker library to update the way that the authentication token is passed
```
diff --git a/slacker/__init__.py b/slacker/__init__.py
index cc06892..8cc5552 100644
--- a/slacker/__init__.py
+++ b/slacker/__init__.py
@@ -66,7 +66,7 @@ class BaseAPI(object):

     def _request(self, request_method, method, **kwargs):
         if self.token:
-            kwargs.setdefault('params', {})['token'] = self.token
+            kwargs.setdefault('headers', {})['Authorization'] = f'Bearer {self.token}'

         url = get_api_url(method)
```

**Comment by jonpas** [comment]
Updated list of _User Token Scopes_ required for the bot:
- channels:history
- channels:read
- channels:write **(new)**
- groups:history
- groups:read
- im:history
- im:read
- mpim:history
- mpim:read
- users:read
