### ISSUE TITLE
slacker.Error: method_deprecated

### ISSUE THREAD

**Issue by miguelperezit** [zach-snell/slack-export#37]
Hi there,
Any plans for updating this amazing tool with the new methods¿?
```
Traceback (most recent call last):
  File "slack_export.py", line 345, in <module>
    bootstrapKeyValues()
  File "slack_export.py", line 245, in bootstrapKeyValues
    channels = slack.channels.list().body['channels']
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 428, in list
    'exclude_members': exclude_members})
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 120, in get
    api, **kwargs
  File "/usr/local/lib/python3.7/site-packages/slacker/__init__.py", line 102, in _request
    raise Error(response.error)
slacker.Error: method_deprecated
```
Thanks!

**Comment by lumbric** [comment]
see #33

**Comment by shanness** [comment]
Does this mean even if you have old legacy tokens you can't use them any more for this?

**Comment by shanness** [comment]
Answered my own question, you CAN use legacy tokens, you just need to use the fork mentioned in #33
